# Generated by Django 5.2 on 2025-05-06 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='leaseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.lease'),
        ),
        migrations.AlterField(
            model_name='application',
            name='propertyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.property'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='propertyId',
            field=models.ForeignKey(db_column='propertyId', on_delete=django.db.models.deletion.CASCADE, to='apps.property'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenantCognitoId',
            field=models.ForeignKey(db_column='tenantCognitoId', on_delete=django.db.models.deletion.CASCADE, to='apps.tenant', to_field='cognitoId'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.lease'),
        ),
        migrations.AlterField(
            model_name='property',
            name='favoritedBy',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='apps.tenant'),
        ),
        migrations.AlterField(
            model_name='property',
            name='locationId',
            field=models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, to='apps.location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='managerCognitoId',
            field=models.ForeignKey(db_column='managerCognitoId', on_delete=django.db.models.deletion.CASCADE, to='apps.manager', to_field='cognitoId'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='properties', to='apps.tenant'),
        ),
    ]
