# Generated by Django 5.2 on 2025-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
