# Generated by Django 5.2 on 2025-05-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tenantCognitoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tenant', to_field='cognitoId'),
        ),
    ]
