version: '3.8'
services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: my-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rental
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no
volumes:
  postgres_data: